<#
.SYNOPSIS
Regenerates tests/fixtures/viewer-cases.json from the PowerShell module.

.DESCRIPTION
The PowerShell engine is the reference implementation. This script runs the
inputs in tests/fixtures/viewer-inputs.json through it and records the exact
results. Pester checks that the file is current, and the Node suite checks that
the browser engine produces the same results.

Run it after changing the engine, a sample runbook, or the inputs, then review
the diff of viewer-cases.json before committing.
#>
[CmdletBinding()]
param(
    [string]$OutputPath = (Join-Path (Join-Path $PSScriptRoot 'fixtures') 'viewer-cases.json')
)

$ErrorActionPreference = 'Stop'
$repositoryRoot = Split-Path -Parent $PSScriptRoot
Import-Module (Join-Path (Join-Path (Join-Path $repositoryRoot 'src') 'DrOrchestrator') 'DrOrchestrator.psd1') -Force

$fixtureRoot = Join-Path $PSScriptRoot 'fixtures'
$inputs = Get-Content -LiteralPath (Join-Path $fixtureRoot 'viewer-inputs.json') -Raw | ConvertFrom-Json

function Get-SampleRunbook {
    param([string]$Name)
    $path = Join-Path (Join-Path (Join-Path $repositoryRoot 'site') 'runbooks') "$Name.json"
    return Get-Content -LiteralPath $path -Raw | ConvertFrom-Json
}

function ConvertFrom-FixtureRunbook {
    param($Source)
    return InModuleScope DrOrchestrator -Parameters @{ Source = $Source } {
        param($Source)
        ConvertTo-DrRunbookDefinition -Runbook $Source
    }
}

$simulations = foreach ($case in $inputs.simulations) {
    $runbook = ConvertFrom-FixtureRunbook (Get-SampleRunbook $case.runbook)
    $execution = Invoke-DrRunbook -Runbook $runbook -Simulation -InjectFailureStepId @($case.failures)
    [ordered]@{
        name = $case.name
        runbook = $case.runbook
        failures = @($case.failures)
        status = $execution.Status
        steps = @($execution.Steps | ForEach-Object {
                [ordered]@{ id = $_.Id; status = $_.Status; message = $_.Message }
            })
    }
}

$plans = foreach ($name in $inputs.plans) {
    $plan = ConvertFrom-FixtureRunbook (Get-SampleRunbook $name) | Get-DrRecoveryPlan
    [ordered]@{
        runbook = $name
        sequentialEstimateSeconds = $plan.SequentialEstimateSeconds
        criticalPathSeconds = $plan.CriticalPathSeconds
        criticalPath = @($plan.CriticalPath)
        missingDurations = @($plan.MissingDurations)
        steps = @($plan.Steps | ForEach-Object {
                [ordered]@{
                    id = $_.Id
                    level = $_.Level
                    earliestStartSeconds = $_.EarliestStartSeconds
                    earliestFinishSeconds = $_.EarliestFinishSeconds
                    onCriticalPath = $_.OnCriticalPath
                }
            })
    }
}

$invalid = foreach ($case in $inputs.invalid) {
    $document = $inputs.base | ConvertTo-Json -Depth 10 | ConvertFrom-Json
    if ($case.PSObject.Properties['remove']) {
        $document.PSObject.Properties.Remove($case.remove)
    }
    if ($case.PSObject.Properties['set']) {
        foreach ($property in $case.set.PSObject.Properties) {
            $document.($property.Name) = $property.Value
        }
    }
    if ($case.PSObject.Properties['step']) {
        $step = $document.steps[$case.step]
        if ($case.PSObject.Properties['removeStep']) {
            $step.PSObject.Properties.Remove($case.removeStep)
        }
        if ($case.PSObject.Properties['setStep']) {
            foreach ($property in $case.setStep.PSObject.Properties) {
                $step | Add-Member -NotePropertyName $property.Name -NotePropertyValue $property.Value -Force
            }
        }
    }

    $errorMessage = $null
    try {
        $runbook = ConvertFrom-FixtureRunbook ($document | ConvertTo-Json -Depth 10 | ConvertFrom-Json)
        if ($case.PSObject.Properties['order']) {
            $null = Get-DrExecutionOrder -Runbook $runbook
        }
    }
    catch {
        $errorMessage = $_.Exception.Message
    }
    if (-not $errorMessage) {
        throw "Invalid fixture '$($case.name)' was accepted by the module."
    }
    [ordered]@{ name = $case.name; runbook = $document; error = $errorMessage }
}

$output = [ordered]@{
    description = 'Generated by tests/Update-ViewerFixtures.ps1 from the PowerShell engine. Do not edit by hand.'
    simulations = @($simulations)
    plans = @($plans)
    invalid = @($invalid)
}
$json = ($output | ConvertTo-Json -Depth 12) -replace "`r`n", "`n"
[System.IO.File]::WriteAllText(
    $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputPath),
    $json + "`n",
    [System.Text.UTF8Encoding]::new($false)
)
